name: dexmv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.0.1=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - addict==2.4.0
    - anyio==3.3.0
    - argcomplete==1.12.3
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - cycler==0.10.0
    - cython==0.29.24
    - debugpy==1.4.1
    - decorator==5.0.9
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.3
    - fasteners==0.16.3
    - glfw==2.1.0
    - gym==0.19.0
    - idna==3.2
    - imageio==2.9.0
    - importlib-metadata==4.8.1
    - ipykernel==6.3.1
    - ipython==7.27.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.4
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==7.0.2
    - jupyter-core==4.7.1
    - jupyter-packaging==0.10.4
    - jupyter-server==1.10.2
    - jupyterlab==3.1.10
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.1
    - jupyterlab-widgets==1.0.1
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mujoco-py==2.0.2.13
    - nbclassic==0.3.1
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.3
    - open3d==0.13.0
    - opencv-python==4.5.3.56
    - packaging==21.0
    - pandas==1.3.2
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.3.2
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygifsicle==1.0.4
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.2.1
    - requests==2.26.0
    - requests-unixsocket==0.2.0
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - send2trash==1.8.0
    - sniffio==1.2.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - tomlkit==0.7.2
    - torch==1.8.1
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==5.1.0
    - transforms3d==0.3.1
    - trimesh==3.9.29
    - typing-extensions==3.10.0.2
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - widgetsnbextension==3.5.1
    - yacs==0.1.8
    - zipp==3.5.0
    - tabulate==0.8.9
    - nlopt==2.7.0
    - click==8.0.0
    - natsort
    - absl-py
    - lxml
